name = "news-bit-worker"
main = "cloudflare-worker/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "USERS_KV"
id = "de165cf7c71a4c6d80a8a095b9034d7e"

[[kv_namespaces]]
binding = "ARTICLES_KV"
id = "6e44ad9545f042cbb51986b53a4921a1"
